export const SET_CURRENT_ADMIN = "SET_CURRENT_ADMIN";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_STUDENT = "SET_CURRENT_STUDENT";
export const SET_CURRENT_ONLINE_EXAM_STUDENT =
  "SET_CURRENT_ONLINE_EXAM_STUDENT";
export const SET_CURRENT_STAFF = "SET_CURRENT_STAFF";
export const SET_CURRENT_STUDENT_INFORMATION =
  "SET_CURRENT_STUDENT_INFORMATION";
export const LOADING = "LOADING";
export const GET_SUCCESS = "GET_SUCCESS";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const GET_ONLINE_MARKS = "GET_ONLINE_MARKS";
export const GET_OVERALL_MARKS = "GET_OVERALL_MARKS";
export const SET_CURRENT_STAFF_INFORMATION = "SET_CURRENT_STAFF_INFORMATION";
export const GET_ONLINE_QUESTION_PAPERS = "GET_ONLINE_QUESTION_PAPERS";
export const GET_OTP = "GET_OTP";
export const GET_CURRENT_EXAMS = "GET_CURRENT_EXAMS";
export const CLEAR_STAFF = "CLEAR_STAFF";
export const GET_QUESTIONS_ONLINE = "GET_QUESTIONS_ONLINE";
export const CLEAR_ONLINE_EXAM = "CLEAR_ONLINE_EXAM";
export const POST_FINAL_SUBMIT = "POST_FINAL_SUBMIT";
