export const SET_CURRENT_ADMIN = "SET_CURRENT_ADMIN";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_STUDENT = "SET_CURRENT_STUDENT";
export const SET_CURRENT_ONLINE_EXAM_STUDENT =
  "SET_CURRENT_ONLINE_EXAM_STUDENT";
export const SET_CURRENT_STAFF = "SET_CURRENT_STAFF";
export const SET_CURRENT_STUDENT_INFORMATION =
  "SET_CURRENT_STUDENT_INFORMATION";
export const LOADING = "LOADING";
export const GET_SUCCESS = "GET_SUCCESS";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
